Docs:
  - docs/**/*
  - examples/**/*
  - licenses/*
  - CITATION
  - .mailmap
  - .readthedocs.yml
  - '*.md'
  - '*.rst'

testing:
  - astropy/tests/**/*
  - astropy/*/tests/*
  - astropy/**/tests/*
  - codecov.yml
  - conftest.py
  - '*/conftest.py'
  - '*/**/conftest.py'
  - azure-pipelines.yml
  - tox.ini
  - .circleci/*
  - .github/*.yml
  - .github/workflows/*.yml
  - .pep8speaks.yml
  - .pyinstaller/**/*
  - .travis.yml

external:
  - astropy/extern/**/*
  - cextern/**/*

installation:
  - docs/install.rst
  - MANIFEST.in
  - pip-requirements
  - pyproject.toml
  - setup.*

Release:
  - docs/development/releasing.rst

config:
  - astropy/config/**/*
  - docs/config/*

constants:
  - astropy/constants/**/*
  - docs/constants/*

convolution:
  - astropy/convolution/**/*
  - docs/convolution/**/*

coordinates:
  - astropy/coordinates/**/*
  - docs/coordinates/*

cosmology:
  - astropy/cosmology/**/*
  - docs/cosmology/*

io.ascii:
  - astropy/io/ascii/**/*
  - docs/io/ascii/*

io.fits:
  - astropy/io/fits/**/*
  - docs/io/fits/**/*
  - cextern/cfitsio/**/*

io.misc:
  - astropy/io/misc/*
  - astropy/io/misc/pandas/**/*
  - astropy/io/misc/tests/**/*
  - docs/io/misc.rst

io.misc.asdf:
  - astropy/io/misc/asdf/**/*
  - docs/io/asdf-schemas.rst

io.registry:
  - astropy/io/*
  - astropy/io/tests/*
  - docs/io/registry.rst

io.votable:
  - astropy/io/votable/**/*
  - docs/io/votable/*

logging:
  - astropy/logger.py
  - astropy/tests/test_logger.py
  - docs/logging.rst

modeling:
  - astropy/modeling/**/*
  - docs/modeling/*

nddata:
  - astropy/nddata/**/*
  - docs/nddata/**/*

samp:
  - astropy/samp/**/*
  - docs/samp/*

stats:
  - astropy/stats/**/*
  - docs/stats/*

table:
  - astropy/table/**/*
  - docs/table/*

time:
  - astropy/time/**/*
  - docs/time/*

timeseries:
  - astropy/timeseries/**/*
  - docs/timeseries/*

uncertainty:
  - astropy/uncertainty/**/*
  - docs/uncertainty/*

unified-io:
  - docs/io/unified.rst

units:
  - astropy/units/**/*
  - docs/units/*

utils:
  - any: ['astropy/utils/**/*', 'docs/utils/*', '!astropy/utils/iers/*', '!astropy/utils/iers/**/*', '!docs/utils/iers.rst']

utils.iers:
  - astropy/utils/iers/**/*
  - docs/utils/iers.rst

visualization:
  - any: ['**/visualization/**/*', '!astropy/visualization/wcsaxes/**/*']

visualization.wcsaxes:
  - astropy/visualization/wcsaxes/**/*
  - docs/visualization/wcsaxes/*

wcs:
  - any: ['**/wcs/**/*', '!astropy/wcs/wcsapi/**/*', '!docs/wcs/wcsapi.rst']

wcs.wcsapi:
  - astropy/wcs/wcsapi/**/*
  - docs/wcs/wcsapi.rst
