name: Cancel duplicate workflows

on:
  workflow_run:
    workflows: ["CI", "CodeQL"]
    types:
      - requested

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - name: Who Am I
      env:
        CONTEXT: ${{ toJson(github.context) }}
        EVENT: ${{ toJson(github.event) }}
      run: echo "See EVENT and CONTEXT"
    - name: Cancel Previous Runs
      uses: pllim/cancel-workflow-action@support-pr-workflow-run
      with:
        workflow_id: ${{ github.event.workflow.id }}
