name: Cancel duplicate workflows

on:
  workflow_run:
    workflows: ["CI", "CodeQL"]
    types:
      - requested

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous runs
      uses: pllim/cancel-workflow-action@support-pr-workflow-run
      with:
        workflow_id: ${{ github.event.workflow.id }}
