name: Cancel duplicate workflows

on:
  workflow_run:
    workflows: ["CI", "CodeQL"]
    types:
      - requested

# Note: This cancels previous runs regardless whether CI is skipped.
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@3d86a7cc43670094ac248017207be0295edbc31d  # 0.8.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
