name: Check PR milestone

on:
  pull_request:
    types: [opened, reopened, milestoned, demilestoned]

jobs:
  milestone:
    name: Check if milestone is set
    runs-on: ubuntu-latest
    steps:
    - name: Check milestone
      uses: actions/github-script@v3
      with:
        script: |
          const pr = context.payload.pull_request;
          if (pr.milestone) {
            core.info(`This pull request has a milestone set: ${pr.milestone.title}`);
          } else {
            core.setFailed("A maintainer needs to set the milestone for this pull request.");
          }
