name: Check PR

on:
  pull_request:

jobs:
  milestone:
    name: Check if milestone is set
    runs-on: ubuntu-latest
    steps:
    - name: Check milestone
      uses: pllim/action-check_milestone_exists@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
