name: Check PR milestone

on:
  # GitHub Help Desk says adding issues will fix it?
  # Not really. It does trigger when milestone happens on PR but no PR info
  # in context, so there is no way to not run this for issues but we don't want to.
  issues:
    types: [opened, milestoned, demilestoned]
  pull_request:
    types: [opened, milestoned, demilestoned]

jobs:
  milestone:
    name: Check if milestone is set
    runs-on: ubuntu-latest
    steps:
    - name: Check milestone
      uses: actions/github-script@v3
      with:
        script: |
          const pr = context.payload.pull_request;
          // This if was suggested by GitHub Help Desk as a workaround.
          if (typeof context.payload.issue.pull_request == "undefined") {
            core.info("This is not a pull request.");
            return;
          }
          if (pr.milestone) {
            core.info(`This pull request has a milestone set: ${pr.milestone.title}`);
          } else {
            core.setFailed("A maintainer needs to set the milestone for this pull request.");
          }
