name: Check external releases

on:
  schedule:
    # Weekly Friday 6 AM build.
    # * is a special character in YAML so you have to quote this string.
    - cron: '0 6 * * 5'

jobs:
  check_releases:
    name: Open issue if new release found
    runs-on: ubuntu-latest
    steps:
    - name: Check CFITSIO release
      uses: pllim/actions-check_cfitsio_release@main
      with:
        CFITSIO_CHECK_N_DAYS: 7
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check WCSLIB release
      uses: pllim/actions-check_wcslib_release@main
      with:
        WCSLIB_CHECK_N_DAYS: 7
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
