name: Check PR change log on label event

on:
  pull_request_target:
    types: [labeled, unlabeled]

# This check also runs on other PR events at ci_workflows.yml.
# It is redefined here for label events to avoid overcomplicating CI logic.
jobs:
  changelog_checker:
    name: Check if change log entry is correct
    runs-on: ubuntu-latest
    steps:
    - name: Check change log entry
      uses: pllim/action-check_astropy_changelog@main
      env:
        CHANGELOG_FILENAME: CHANGES.rst
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
