name: CI

on:
  push:
    branches:
      - v4.2.x
  pull_request_target:
    branches:
      - v4.2.x

jobs:
  basebranch:
    name: Check base branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      if: github.event_name == 'pull_request'
      with:
        script: |
          const skip_label = 'skip-basebranch-check';
          const allowed_basebranch = 'master';
          const pr = context.payload.pull_request;
          if (pr.base.ref !== allowed_basebranch) {
            core.setFailed(`PR opened against ${pr.base.ref}, not ${allowed_basebranch}`);
          }

  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: basebranch
    strategy:
      fail-fast: true
      matrix:
        include:

          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle

          - name: Python 3.7 with minimal dependencies
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test

          - name: Python 3.8 with all optional dependencies
            os: ubuntu-latest
            python: 3.8
            toxenv: py38-test-alldeps
            toxargs: -v --develop
            toxposargs: --open-files

          # NOTE: In the build below we also check that tests do not open and
          # leave open any files. This has a performance impact on running the
          # tests, hence why it is not enabled by default.
          - name: Python 3.7 with oldest supported version of all dependencies
            os: ubuntu-16.04
            python: 3.7
            toxenv: py37-test-oldestdeps

          - name: Python 3.7 with numpy 1.17 and full coverage
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test-alldeps-numpy117-cov-clocale
            toxposargs: --remote-data=astropy

          - name: Python 3.8 with all optional dependencies (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38-test-alldeps
            toxposargs: --durations=50

          - name: Python 3.7 with all optional dependencies (MacOS X)
            os: macos-latest
            python: 3.7
            toxenv: py37-test-alldeps
            toxposargs: --durations=50

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install language-pack-de and tzdata
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install language-pack-de tzdata
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    # TODO: Do we need --gcov-glob "*cextern*" ?
    - name: Upload coverage to codecov
      if: ${{ contains(matrix.toxenv,'-cov') }}
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml

  allowed_failures:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: basebranch
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: (Allowed Failure) Python 3.7 with remote data and dev version of key dependencies
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test-devdeps
            toxposargs: --remote-data=any

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install language-pack-de and tzdata
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install language-pack-de tzdata
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
