name: When Opened

on:
  issues:
    types:
    - opened
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR
      uses: actions/labeler@main
      if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Special comment
      uses: pllim/action-special_pr_comment@ts-action
      with:
        SPECIAL_DAYS: 04-01,12-23
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
